### ISSUE TITLE
유저는 게시글 CRUD할 수 있다.

### ISSUE THREAD

**Issue by han-sy** [han-sy/intern-2020#1]

**Comment by myabcc17** [comment]
- [x] WYSIWYG 에디터 리서치하기
CKEditor 4 사용

- [x] 게시글 작성 Form jsp 개발

**Comment by myabcc17** [comment]
**게시글 작성폼은 다른 페이지 호출 없이 게시판 조회 하는 창에서 로드한다.**

***



> 게시글 작성 폼 에디터 적용완료

- CKEditor 4 Standard version 적용

**Comment by myabcc17** [comment]
게시글 삽입 쿼리 개발 이슈
---
**Mybatis mapper에서 쿼리는 생성이 됐는데 결과값이 'unread'로 출력됨** 

- mapper의 resultType 설정을 DTO로 했어야 했는데 primitive Type인 int로만 하여 board_id만 뜨고 나머지 Column들은 모두 'unread' 상태로 출력됐음. resultType 수정 후 해결됨.

`    <select id="getBoard_id" parameterType="hashmap" resultType="com.board.project.blockboard.dto.BoardDTO">`
- Data 중 한글로 된 것들은 읽어오지 못해서 jdbc 커넥션에서 encodingType 명시

`    url: jdbc:mysql://localhost:3306/block_board?serverTimezone=UTC&characterEncoding=utf8`

**Comment by myabcc17** [comment]
게시글 수정, 삭제 버튼 추가
---
**게시글 조회 시 로그인된 유저와 게시글 작성자가 같을 경우에만 '수정', '삭제' 버튼을 표시한다.**

- 원래는 Interceptor에서 sessionID쿠키와 userID쿠키를 검증한 후에 Controller로 보내서 쿠키변조를 막아야하는데, 약식으로 개발하였다.

**Comment by myabcc17** [comment]
게시글 수정, 삭제 기능 완성
---
**수정기능**
- 수정버튼 클릭 시, 폼을 띄우고 현재 보고있는 게시글의 정보를 에디터로 불러온다.
- 게시글이 등록될 게시판과 게시글의 제목, 내용만 변경할 수 있게 설정하였다.
- '수정하기' 버튼 클릭 시, postID와 수정한 게시글의 게시판명, 제목, 내용을 서버로 보낸다.
- 서버는 요청이 온 postID로 PostDTO를 조회한다.
- 조회한 PostDTO의 companyID와 요청이 온 게시글의 게시판명으로 수정할 boardID를 조회 후 set한다.
- 그 다음, 데이터베이스에 UPDATE를 실행하고, 현재 페이지를 새로고침하지 않고 게시글 목록을 새로 요청하여 받아와 수정 후 게시글 목록을 보여준다

**삭제기능**
- 삭제버튼 클릭 시, 현재 postID를 서버로 보낸다.
- 서버는 요청이 온 postID로 DELETE 쿼리를 실행한 후, 현재 페이지를 새로고침 하지 않고 게시글 목록을 새로 요청하여 받아와 삭제 후 게시글 목록을 보여준다

**Comment by myabcc17** [comment]
게시글 관련 js파일분리
---
postEvent.js -> 게시글 CRUD관련 버튼 이벤트 등록 & 함수 호출 파일
postAjax.js   -> 게시글 CRUD관련 이벤트에서 호출하는 함수가 있는 파일
