### ISSUE TITLE
데이터베이스 CRUD시 데이터 유효성 검사

### ISSUE THREAD

**Issue by Dong-wook94** [han-sy/intern-2020#112]
전반적으로 CRUD시 데이터 유효성 검사부분 정리하여 수정하기

**Comment by myabcc17** [comment]
## 게시글 작성, 수정시 Post 객체 유효성 검증
* LengthCheckUtils, LengthValidException 클래스를 생성하였음.
* 검증과정은 Controller에서 진행한다.
* LengthCheckUtils의 isValid(anyDTO) 함수에서 들어오는 객체의 글자수 제한이 있는 Attribute를 byte[]로 바꾸어 길이를 계산 후 검증하여 Y/N을 반환한다.
* 해당 과정에서 검증이 안될 시 LengthValidException이 발생하여 서비스를 호출하지 않고 브라우저에 BAD_REQUEST_ERROR 코드(=400)를 전송한다.
