### ISSUE TITLE
input시 length 제한 걸기

### ISSUE THREAD

**Issue by Dong-wook94** [han-sy/intern-2020#117]
* [ ] 게시판 추가
* [ ] 게시판 이름변경
* [ ] 댓글
* [ ] 답글

**Comment by myabcc17** [comment]
- [x] 게시글 제목

- [x] 게시글 내용

**Comment by myabcc17** [comment]
## 게시글 작성, 수정시 Post 객체 길이검사
* LengthCheckUtils 클래스를 생성하여 안에 함수를 구현하였다.
* 검증과정은 Controller에서 진행한다.
* LengthCheckUtils의 isValid(anyDTO) 함수에서 들어오는 객체의 글자수 제한이 있는 Attribute를 byte[]로 바꾸어 길이를 계산 후 검증하여 Y/N을 반환한다.
* 해당 과정에서 검증이 안될 시 Client에게 에러와 메세지를 전송한다.

`for(b=i=0;c=str.charCodeAt(i++);b+=c>>11?3:c>>7?2:1);`
1. str 의 문자를 하나씩 가져온다.
2. str 을 2048로 나누었을 때 몫이 있으면 2048보다 큰 유니코드이므로 3byte 
3. 아닐경우 128로 나누었을 때 몫이 있으면 128보다 큰 유니코드이므로 2byte
4. 셋 다 아니면 1byte로 계산하여 b에 더한 후 return 한다.

> 유니코드 참고 표

![image](https://user-images.githubusercontent.com/43199300/73800745-9546d780-47fc-11ea-8301-461291d18fd5.png)

**Comment by myabcc17** [comment]
- [ ] 회원추가 폼
