### ISSUE TITLE
@RequestParam, @PathVariable 리팩토링

### ISSUE THREAD

**Issue by Dong-wook94** [han-sy/intern-2020#82]
넘어오는 parameter 의 key 와 spring 에서 받는 key 값이 같으면  @RequestParam에 key 를 명시하지 않아도 됩니다.

_Originally posted by @han-sy in https://github.com/han-sy/intern-2020/pull/64_

**Comment by myabcc17** [comment]
* 대소문자 구분하기, @PathVariable 은 모두 소문자, '-' 추가
* 명시 규칙 수정하기
